---
# These are supported funding model platforms
github: cooljeanius
patreon: EricGallager
ko_fi: ericgallager  # (will intentionally stay OOS w/other repo)
liberapay: Wesnoth
open_collective: cooljeanius
